package org.apache.hadoop.fs;

/** Generated by rm commands */
public class PathIsNotEmptyDirectoryException extends PathExistsException {
  /** @param path for the exception */
  public PathIsNotEmptyDirectoryException(String path) {
    super(path, "Directory is not empty");
  }
}